version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    restart: always
    volumes:
      - .:/sources/
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin2
      - DJANGO_SUPERUSER_PASSWORD=27474129
    command: sh -c "python3 manage.py migrate && python3 manage.py createsuperuser --email=admin@admin.com --noinput && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
      - adminer
    networks:
      - projectnetwork

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "27474129"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - '54322:5432'
    networks:
      - projectnetwork

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - projectnetwork

networks:
  projectnetwork:
    driver: bridge